dotnet: 5.0
script:
  - ./build.ps1 --branchName=$TRAVIS_BRANCH --ciPlatform='travis' --nugetServer=$NugetServer --nugetApiKey=$NugetApiKey

branches:
  only:
  - master
  - develop

os: windows

notifications:
  email: false