language: csharp
dotnet: 5.0
mono: none
script:
  - ./build.sh --branchName=$TRAVIS_BRANCH --ciPlatform='travis' --nugetApiKey=$NugetApiKey

branches:
  only:
  - master

notifications:
  email: false