version: "3.4"

services:

  messagestorage-sample-web-api-sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Passw0rd"
    expose:
      - 6137
    ports:
      - "6137:1433"


  messagestorage-sample-web-api-postgres:
    image: postgres:9.5.25-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 6138
    ports:
      - "6138:5432"
        
  messagestorage-sample-web-api-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=message_storage
      - MYSQL_ROOT_PASSWORD=example
    expose:
      - 6139
    ports:
      - "6139:3306"